version: '3'

services:
  postgres:
    image: 'postgres:latest'
    container_name: e_university_api-postgres
    env_file:
      - .env  # must define POSTGRES_USER, POSTGRES_PASSWORD and POSTGRES_DB
    volumes:
      - database-data:/var/lib/postgresql/data/  # persist data
    ports:
      - '5432:5432'  # required to access DB from host system
  backend:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: e_university_api-backend
    environment:
      # override values from .env file to ensure they are valid for compose networking
      # https://docs.docker.com/compose/networking/
      POSTGRES_HOST: 'postgres'
      POSTGRES_PORT: '5432'
    env_file:
      - .env
    depends_on:
      - postgres
    command: uvicorn --host 0.0.0.0 --port 8000 main:app
    ports:
      - '8000:8000'

volumes:
  database-data:

